---

- hosts: all
  tasks:
  - name: Add SSH keys
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ item }}"
    loop: "{{ ssh_keys + additional_ssh_keys | unique }}"

  - name: Disable password login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^(#\s*)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
    when: disable_password_login

- hosts: cluster
  become: true
  roles:
  - role: rpi/common  # sets facts for subsequent roles!
  - role: rpi/gps_sync
    when: raspberry_pi|default(false)

  - role: wireguard

# Install K3S
- hosts: cluster
  gather_facts: true
  become: true
  roles:
  - role: k3s/prereq
  - role: k3s/download

- hosts: master
  become: true
  roles:
  - role: k3s/master

- hosts: node
  become: true
  roles:
  - role: k3s/node

- hosts: master
  become: true
  roles:
  - role: riasc
