---

- hosts: all
  tasks:
  - name: Add SSH keys
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ item }}"
    loop: "{{ ssh_keys + additional_ssh_keys | unique }}"

  - name: Disable password login
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: '^(#\s*)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
    when: disable_password_login
  
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: rpi
    - role: rpi-wireguard
    - role: rpi-gps-sync

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: master
  become: yes
  roles:
  - role: riasc
