---
- name: Install build-time depenencies for Wireguard
  apt:
    name:
    - raspberrypi-kernel
    - raspberrypi-kernel-headers
    state: latest  # noqa package-latest
  notify:
  - reboot
  - reboot_local

- name: Add keys for backports repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 04EE7237B7D453EC

- name: Add Debian backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    filename: backports.list
    update_cache: true

- name: Install Wireguard DKMS
  apt:
    name: wireguard
    state: present
    default_release: buster-backports

- name: Load Wireguard module during system startup
  lineinfile:
    path: /etc/modules
    line: wireguard

# Make sure we have booted to the latest kernel before loading the freshly build Wireguard module
- name: Flush handlers
  meta: flush_handlers

- name: Load Wireguard module
  modprobe:
    name: wireguard
