---

- name: Execute OS related tasks on the Raspberry Pi
  include_tasks: "{{ item }}"
  with_first_found:
    - "prereq/{{ detected_distribution }}-{{ detected_distribution_major_version }}.yml"
    - "prereq/{{ detected_distribution }}.yml"
    - "prereq/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "prereq/{{ ansible_distribution }}.yml"
    - "prereq/default.yml"

- name: Load Wireguard module during system startup
  lineinfile:
    path: /etc/modules
    line: wireguard

# Make sure we have booted to the latest kernel before loading the freshly build Wireguard module
- name: Flush handlers
  meta: flush_handlers

- name: Load Wireguard module
  modprobe:
    name: wireguard
