---
all:
  hosts:
    local:
      ansible_host: 127.0.0.1

  children:
    master:
      hosts:
        kubernetes-k3s-master-1.os-cloud.eonerc.rwth-aachen.de:
          ansible_user: ubuntu

        riasc-master-0.edgy.vms.0l.de:
          ansible_user: core

    node:
      hosts:
        kubernetes-k3s-worker-[1:2]:

        rpi-ait-1:
        rpi-aurelius-[1:4]:
        rpi-turpin-1:
        rpi-dtu-1:
        rpi-dtu-syslab-1:
        rpi-rwth-[1:4]:
        rpi-tec-1:
        rpi-tud-1:
        rpi-uos-1:
        rpi-vtt-[1:4]:
        rpi-cea-1:
        rpi-oct-1:

        ntnu-1:
          ansible_host: 10.101.8.4
          ansible_user: nsgl
          disable_password_login: false

        vm-rwth-svg-1:
          ansible_user: stv0g

        infis-pi.acs-lab.eonerc.rwth-aachen.de:
          ansible_user: vogel

    cluster:
      children:
        master:
        node:

    rpi:
      hosts:
        rpi-ait-1:
        rpi-aurelius-[1:4]:
        rpi-turpin-1:
        rpi-dtu-1:
        rpi-dtu-syslab-1:
        rpi-rwth-[1:4]:
        rpi-tec-1:
        rpi-tud-1:
        rpi-uos-1:
        rpi-vtt-[1:4]:
        rpi-cea-1:
