- name: Disable HCI UART
  systemd:
    name: hciuart
    state: stopped
    enabled: false

- name: Disable Systemd timesync daemon
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false

- name: Enable PPS-GPIO device tree overlay
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=pps-gpio,gpiopin={{ rpi_gps_sync_pps_pin }}
  register: config_dt_pps

- name: Disable Bluetooth on Raspberry Pi 4
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=disable-bt
  register: config_dt_bt

- name: Disable console on UART0
  replace:
    path: /boot/cmdline.txt
    regexp: 'console=(serial0|ttyAMA0|ttyS0)(,\d+)?'
    replace: ''
  register: cmdline_uart

- name: Trigger reboot if cmdline changed
  meta: noop
  changed_when: (config_dt_pps is changed or config_dt_bt is changed or cmdline_uart is changed) and ansible_connection != 'local'
  notify: reboot

- name: Trigger reboot if cmdline changed
  meta: noop
  changed_when: (config_dt_pps is changed or config_dt_bt is changed or cmdline_uart is changed) and ansible_connection == 'local'
  notify: reboot_local

